FROM heroku/heroku:16
LABEL maintainer="maxmiliano.pizarro.5@gmail.com"
ADD pg-restore.sh /pg-restore.sh
RUN chmod +x /pg-restore.sh 

# set the startup command to execute the jar
EXPOSE 8080
CMD /start.sh 


