FROM tomcat:8.0-alpine
LABEL maintainer="maxmiliano.pizarro.5@gmail.com"
ADD pg-restore.sh /pg-restore.sh
RUN chmod +x /pg-restore.sh 

ADD target/rdp-gcba.war /usr/local/tomcat/webapps/

# set the startup command to execute the jar
EXPOSE 8080
CMD ["catalina.sh", "run"]


